== Service Errors

The NetAPI common schema xref:References[[2]] defines the error formats for this API. From the
specification an example ServiceException is:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?> <common:requestError xmlns:common="urn:oma:xml:rest:netapi:common:1">
<serviceException>
<messageId>SVC0004</messageId> <text>No valid addresses provided in message part %1</text> <variables>address</variables>
</serviceException>
</common:requestError>
----

This section provides some additional information on how these errors apply to
the HATA SMS enabler. Unless otherwise stated the specification is the key
reference point for all definitions. All errors generated by this enabler will
use the ServiceException and PolicyException syntax as defined by the Net API
specification xref:References[[2]].

=== Error Response MessageId and Status Code

Message IDs are defined by the Net API specification. The following message IDs
are in use by the Net API service. Status codes are the HTTP status code in
which the REST response will be supplied.

[options="header"]
|=======================
|MessageId |Description |Status Code
|SVC0001 |General service exception.
Consult variables field for finer grained error code. |400
|SVC0002 |Invalid Input Value |400
|SVC0004 |No valid addresses |400
|SVC0005 |Duplicate correlator error |409
|SVC0280 |Message too long |403
|POL0001 |General policy error.
Consult variables field for finer grained error code. |403
|POL0008 |Charging not allowed. |403
|POL0011 |Media Type Not Supported |406
|=======================

=== Error Response Variables

Variables is an unbound String set whereby the enabler may add additional
diagnostic information. SAM will use the variables field to add an error code to
the error response providing more granular diagnostics. The error codes list is
subject to change as service features supported by the enabler grows. The
current list of error codes is:

[options="header"]
|=======================
|Error Code |Description
|POL-GW-001 |Operation Not Supported
|POL-GW-002 |TPA has exceeded maximum allowed rate of transactions.
|POL-GW-003 |Access forbidden for TPA.
|POL-GW-004 |Forbidden operation.
|POL-SMS-001 |Message retry strategy forbidden.
|POL-SMS-002 |Message retry min interval exceeded.
|POL-SMS-003 |Message retry max timer exceeded.
|=======================
