version: "2"

services:

  netapismsenabler:
    environment:
       SPRING_PROFILES_ACTIVE: bell_lab

  smsxenabler:
    environment:
       SPRING_PROFILES_ACTIVE: bell_lab

  callbacksimulator:
    image: "vennetics/bell-sam-callback-simulator:0.0.5.2"
    hostname: callbacksimulator
    container_name: "callbacksimulator"
    restart: always
    depends_on:
      - discoveryservice
      - configserver
    volumes_from:
      - logaggregator
    environment:
       EUREKA_URL: "http://vennetics:M5NLqZD8ivv0@discoveryservice:8761/eureka/"
