version: "2"

services:

  cassandradataaggregator: 
    image: "vennetics/bell-sam-logaggregator:0.0.5.1"
    volumes:       
      - ~/cassandra/lib:/var/lib/cassandra
      - ~/cassandra/log:/var/log/cassandra
      
  cassandra:
    image: "cassandra:2.2"
    volumes_from:
      - cassandradataaggregator
    depends_on:
      - cassandradataaggregator