version: "2"

services:

  logaggregator: 
    image: "vennetics/bell-sam-logaggregator:0.0.3.0"
    volumes:       
      - ~/samlogs:/var/log/sam/
      
  cassandra:
    image: "cassandra:2.2"
    restart: always

  discoveryservice:
    image: "vennetics/bell-sam-discovery-service:0.0.3.0"
    restart: always
    hostname: discoveryservice
    container_name: "discoveryservice"
    restart: always
    volumes_from:
      - logaggregator
    depends_on:
      - logaggregator
#      - cassandra
    ports:
      - "8761:8761"
    environment:
       REGISTER_WITH_OTHER_EUREKA_NODES : "false"
       EUREKA_URL: "http://vennetics:M5NLqZD8ivv0@discoveryservice:8761/eureka/"

  configserver:
    image: "vennetics/bell-sam-config-server:0.0.3.0"
    restart: always
    depends_on:
      - discoveryservice
    volumes_from:
      - logaggregator
    environment:
       EUREKA_URL: "http://vennetics:M5NLqZD8ivv0@discoveryservice:8761/eureka/"
       GIT_URI: "git@bell-sam-config.github.com:Vennetics/bell-sam-config.git"
  
  apigatewayserver:
    image: "vennetics/bell-sam-api-gateway-server:0.0.3.0"
    restart: always
    depends_on:
      - discoveryservice
      - configserver
      - adminserver
    volumes_from:
      - logaggregator
    environment:
       EUREKA_URL: "http://vennetics:M5NLqZD8ivv0@discoveryservice:8761/eureka/"
    ports:
      - "8087:8087"
  
  subscriberthirdpartysdmserver:
    image: "vennetics/bell-sam-subscriber-thirdparty-sdm-server:0.0.3.0"
    restart: always
    depends_on:
      - discoveryservice
      - configserver
    volumes_from:
      - logaggregator
    environment:
       EUREKA_URL: "http://vennetics:M5NLqZD8ivv0@discoveryservice:8761/eureka/"

  hystrixdashboard:
    image: "vennetics/bell-sam-hystrix-dashboard:0.0.3.0"
    restart: always
    depends_on:
      - discoveryservice
      - configserver
    volumes_from:
      - logaggregator
    environment:
       EUREKA_URL: "http://vennetics:M5NLqZD8ivv0@discoveryservice:8761/eureka/"

  turbine:
    image: "vennetics/bell-sam-turbine:0.0.3.0"
    restart: always
    depends_on:
      - discoveryservice
      - configserver
    volumes_from:
      - logaggregator
    environment:
       EUREKA_URL: "http://vennetics:M5NLqZD8ivv0@discoveryservice:8761/eureka/"

  helloworld:
    image: "vennetics/bell-sam-helloworld:0.0.3.0"
    restart: always
    depends_on:
      - discoveryservice
      - configserver
    volumes_from:
      - logaggregator
    environment:
      EUREKA_URL: "http://vennetics:M5NLqZD8ivv0@discoveryservice:8761/eureka/"

  springbootadmin:
    image: "vennetics/bell-sam-spring-boot-admin:0.0.3.0"
    restart: always
    depends_on:
      - discoveryservice
      - configserver
    volumes_from:
      - logaggregator
    environment:
       EUREKA_URL: "http://vennetics:M5NLqZD8ivv0@discoveryservice:8761/eureka/"
    ports:
      - "8094:8094"
  
  netapismsenabler:
    image: "vennetics/bell-sam-netapi-sms-enabler:0.0.3.0"
    restart: always
    depends_on:
      - discoveryservice
      - configserver
    volumes_from:
      - logaggregator
    environment:
       EUREKA_URL: "http://vennetics:M5NLqZD8ivv0@discoveryservice:8761/eureka/"
       SPRING_PROFILES_ACTIVE: simulator
  
  smsxenabler:
    image: "vennetics/bell-sam-smsx-enabler:0.0.3.0"
    restart: always
    depends_on:
      - discoveryservice
      - configserver
    volumes_from:
      - logaggregator
    environment:
       EUREKA_URL: "http://vennetics:M5NLqZD8ivv0@discoveryservice:8761/eureka/"
       SPRING_PROFILES_ACTIVE: simulator

  examplecassandraspringdatarest:
    image: "vennetics/bell-sam-example-cassandra-spring-data-rest:0.0.3.0"
    restart: always
    depends_on:
      - discoveryservice
      - configserver
      - cassandra
    volumes_from:
      - logaggregator
    environment:
      EUREKA_URL: "http://vennetics:M5NLqZD8ivv0@discoveryservice:8761/eureka/"

  adminserver:
    image: "vennetics/bell-sam-admin-server:0.0.3.0"
    restart: always
    depends_on:
      - discoveryservice
      - configserver
      - cassandra
    volumes_from:
      - logaggregator
    environment:
      EUREKA_URL: "http://vennetics:M5NLqZD8ivv0@discoveryservice:8761/eureka/"
  
networks:
  default:
    external:
      name: bellsam
