spring:
  application:
    name: discoveryservice
server:
  port: ${PORT:8761}
shell:
  ssh:
    port: 2010
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}
  client:
    registerWithEureka: ${REGISTER_WITH_OTHER_EUREKA_NODES:false}
    fetchRegistry: ${REGISTER_WITH_OTHER_EUREKA_NODES:false}
    serviceUrl: 
      defaultZone: ${EUREKA_URL:http://vennetics:M5NLqZD8ivv0@localhost:8761/eureka/}
    server:
      waitTimeInMsWhenSyncEmpty: 0
security:
  user:
    name: ${eureka.username:vennetics}
    password: ${eureka.password:M5NLqZD8ivv0}
