= Developer Guide: Naming Conventions
Vennetics Ltd;
:doctype: book
:icons: font
:toc:
:toc-placement: preamble
:source-highlighter: coderay
:coderay-linenums-mode: inline
:coderay-css: class
:revdate: 7th March 2016
:revnumber: 1.0

This document describes the naming conventions that should be used in Vennetics projects.

The key goals within these conventions are:

* Ensure consistent naming across the project by all developers.
* Ensure we avoid naming collisions or unexpected configuration loading by fully qualifying all deliverables.
* Make it easy to identify the nature of a project or class from the name.

== Modules and Projects

All projects and modules should follow the Maven style naming conventions as described here https://maven.apache.org/guides/mini/guide-naming-conventions.html

Specifically:

* Each repo will map to a single build which may consist of multiple projects.
* The build will be identified by a unique group Id.
** Group IDs in use so far are:
*** com.vennetics.bell.sam for the bell-sam repo
*** com.vennetics.microservices.common for the microservices common repo.
* The artifact ID will be set in the build.gradle and all deliverables within the same group shall use the same prefix.
** e.g. bell-sam-api-gateway, bell-sam-core-errors etc
* Version will be managed based on project deliverables and releases.

== Packages and Namespaces

* Each project *must* have a unique root package name.
* The package name should start with the group ID.
* The package should be further qualified based on the artifact ID.
** e.g. com.vennetics.microservices.common.core.hystrix for a core-hystrix module in the com.vennetics.microservices.common group.

== Module Names/Group IDs

Module names should reflect the nature of the project using an appropriate prefix or suffix. To date we have the following categories of projects:

[options="header"]
|=======================
| Category | Naming Rule | Example |
| Spring-Boot microservice | server suffix. The name should also uniquely identify the service being exposed. e.g. if it's specific to a particular interface within a standard containing many interfaces the name should be qualified accordingly. If the microservice is an enabler mapping between two protocols the underlying protocol should be included in the name too. | netapi-sms-v1-smpp-server, parlayx-location-v2_1-mlp-server |
| Spring-boot starter | spring-boot-starter prefix | spring-boot-starter-logging |
| Spring-data Cassandra repository or model | data-model suffix | admin-data-model |
| Service layer API | service-api suffix | netapi-sms-v1-service-api |
| Network Adapter layer API | adapter-api suffix | sdm-adapter-api |
| Service layer Implementation | service suffix | netapi-sms-v1-service |
| Network Adapter layer Implementation | adapter suffix | sdm-adapter |
| Gateway Adapter | gateway-adapter suffix | netapi-gateway-adapter |
| Library protocol mapper | lib prefix. Protocol suffix | lib-ldap |
| Schema definition | Specification prefix qualified to same level as the project contents. Schema file suffix (e.g. wsdl). The namespace within the schema should be used to create the name. If the module is specific to a version of the schema it should be included in the name. If the module is specific to an service or interface within the schema they should also be included. | parlayx-wsdl or parlayx-2_1-wsdl or parlayx-sms-2_1-wsdl. |
| Autogenerated from schema | spring-boot-starter prefix | spring-boot-starter-logging |
|=======================

All deliverables related to a single micro-service delivery should also share the same prefix where appropriate.

== Hystrix Commands

* All Hystrix commands should have a "Command" suffix.
* All must have a command name that can uniquely identify the command within the scope of a delivery e.g. SendSms is not enough as it could be Text or Binary and NetAPI or OneAPI.
* All commands accessing a shared resource (e.g. same HTTP connection) should share a command group name which is unique to that resource.
* Command names should be UpperCamelCase
* Group names should be UpperCamelCase

== Configuration

* All configuration for services should use YML format.
* All Vennetics defined config keys should have a group ID scope prefix. e.g. com.vennetics.microservices.common
* Further to the group scope the group ID should be used to further scope the config key.
* The additional-spring-configuration-metadata.json file should be created describing the config settings.
* Spring profiles should be used to separate configuration settings for different environments.
* Where the above isn't sufficient to fully distinguish a key (e.g. because more than one instance of a service will be loaded with different configs) then the key should be further qualified with some logical identity.
* @EnableAutoConfiguration must never be used except in a microserver project where all services are being wired together. Use @Import with component scanning instead or spring-boot-starters.

== Classes and Interfaces

Naming of classes and interfaces should follow standard Java naming conventions. Some additional conventions are in place for Vennetics code.

* SLF4J loggers must be called logger
* All interfaces should have an "I" name prefix e.g. IMyInterface
* All spring configuration files should have a "Config" suffix e.g. LoggingConfig
* All Spring-Data repositories should have a Repository suffix e.g. IMyTableRepository
* All composite primary keys should have a PrimaryKey suffix.
* Service layer interfaces should have a Service suffix.
* Spring Controllers should have a Controller suffix.
* AOP advice classes should have an Advice suffix.
* Adapter interfaces should have an Adapter suffix.
* Spring Applications should have an Application suffix.
